#define MOTOR_PWM1 12
#define MOTOR_PWM2 13
#define MOTOR_PWM3 14
#define MOTOR_PWM4 15

#define EMERGENCY_BUTTON 4
#define BLUETOOTH_LED 2

#define SAMPLING_TIME_MS 14
#define RECEIVE_DATA_SIZE 7
#define PID_MAX 2000
#define LIMIT_MOTOR 255

#define IMU_CNT_START_NUM 100
#define IMU_CNT_TOTAL_NUM 100
#define CTL_CNT_START_NUM 150
#define CTL_CNT_TOTAL_NUM 100