version: "3"

services:
    api:
        container_name: api
        restart: always
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - /record:/record
        network_mode: host

    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /record:/record
        network_mode: host

    tunnel:
        container_name: tunnel
        build:
            context: ./tunnel
            dockerfile: Dockerfile
        restart: unless-stopped
        network_mode: host
        env_file:
            - .env
