version: "3"

services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "1935:1935"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/rtmp.conf:/etc/nginx/rtmp.conf

        depends_on:
            - signaling_server
        links:
            - signaling_server
        networks:
            - frontend
            - backend

    signaling_server:
        container_name: signaling_server
        restart: unless-stopped
        build:
            context: ./signaling_server
            dockerfile: Dockerfile
        environment:
            TZ: Asia/Tokyo
        networks:
            - backend

    auth_server:
        container_name: auth_server
        restart: unless-stopped
        build:
            context: ./auth-api
            dockerfile: Dockerfile
        networks:
            - backend

    mysql:
        container_name: mysql-db
        image: mysql-db:latest
        restart: unless-stopped
        build:
            context: ./mysql
            dockerfile: Dockerfile
        volumes:
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
            - mysql-data:/var/lib/mysql
        env_file:
            - ./mysql/mysql.env
        networks:
            - backend

    tunnel_server:
        container_name: tunnel_server
        restart: unless-stopped
        build:
            context: ./tunnel_server
            dockerfile: Dockerfile
        #networks:
        #    - backend
        #    - frontend
        network_mode: host

volumes:
    mysql-data:

networks:
    frontend:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/16
    backend:
        internal: true
